apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- environment-manager.yaml

images:
- name: environment-manager
  newName: gitlab-registry.cern.ch/aliceo2group/dockerfiles/aliecs/environment-manager
  newTag: latest
