---
o2:
  roleclasses:
    readout:
      wantsCPU: 1
      wantsMemory: 256
      wantsPorts: ""
      command:
        env: "[\"FOO=/bar/quux\", \"BAR=baz\"]"
        shell: true
#        value: source /etc/profile.d/modules.sh && \
#                      MODULEPATH={{ o2_install_path }}/modulefiles module load {{ flpprototype_readout_packagebasename }}/{{ flpprototype_readout_packageversion }} && \
#                      {{ o2_install_path }}/{{ flpprototype_readout_packagebasename }}/{{flpprototype_readout_packageversion}}/bin/o2-readout-exe file:{{ flpprototype_readout_confdir }}/{{ flpprototype_readout_default_config }} | {{ infologger_install_path }}/bin/log -x
        value: source /etc/profile.d/modules.sh &&
                      MODULEPATH=/opt/alisw/el7/modulefiles module load Readout &&
                      /opt/alisw/el7/Readout/v0.1.0-16/bin/o2-readout-exe file:/etc/flpprototype.d/readout/configDummy.cfg | /opt/o2-InfoLogger/bin/log -x
        arguments: "[]"
    qctask:
      wantsCPU: 1
      wantsMemory: 256
      wantsPorts: "3000-3002"
      command:
        env: "[]"
        shell: true
        arguments: "[]"
        value: source /etc/profile.d/modules.sh &&
               MODULEPATH=/opt/alisw/el7/modulefiles module load QualityControl &&
               MODULEPATH=/opt/alisw/el7/modulefiles module load Control-OCCPlugin &&
               MODULEPATH=/opt/alisw/el7/modulefiles module list &&
               qcTaskLauncher
               -n myTask_1 -c json:///etc/flpprototype.d/qc/example-default.json
               --id myTask_1 --mq-config /etc/flpprototype.d/qc/alfa.json
               --severity trace --color false
               -S $CONTROL_OCCPLUGIN_ROOT/lib/
               -P OCC --controlport 47101
  roles:
    readout01:
      roleClass: readout
    qctask02:
      roleClass: qctask


  deployment:
    o2_install_path: /opt/alisw/el7
    flpprototype_packagebasename: flpproto
    flpprototype_packageversion: v0.1.0-16
    flpprototype_readout_confdir: /etc/flpprototype.d/readout
    flpprototype_readout_default_config: configDummy.cfg
    flpprototype_readout_packagebasename: Readout
    flpprototype_readout_packageversion: v0.1.0-16
    flpprototype_readoutcard_packagebasename: ReadoutCard
    flpprototype_readoutcard_packageversion: v0.8.7-1
    small_hugepages_count: 128
    large_hugepages_count: 0
    flpprototype_qc_confdir: /etc/flpprototype.d/qc
    flpprototype_qc_default_config: example-default.ini
    flpprototype_qc_fairmq_config: alfa.json
    flpprototype_qc_packagebasename: QualityControl
    flpprototype_qc_packageversion: v0.3.0-2
    infologger_install_path: /opt/o2-InfoLogger
    infologger_confdir: /etc

