--- 
controlport: 47102
executor: /opt/o2control-executor
mesosurl: "http://aidrefsrv21.cern.ch:5050/api/v1/scheduler"
verbose: true
veryverbose: true
globalconfigurationuri: "file://hacking/config.yaml"
coreWorkingDir: "/home/teo/workspace/aliecs.d"
