site_name: aliecs

nav:
    - 'Handbook':
        - 'Introduction': 'docs/handbook/introduction.md'
        - 'Basic Concepts': 'docs/handbook/concepts.md'
        - 'Design Overview': 'docs/handbook/overview.md'
        - 'Workflow and Task Config.': 'docs/handbook/configuration.md'
        - 'Environment Operation Order': 'docs/handbook/operation_order.md'
        - 'Workflow Variables': '../controlworkflows'
    - 'Component reference':
        - 'AliECS GUI': 'hacking/COG.md'
        - 'AliECS core':
            - 'Integrated Services': 'core/integration/README.md'
            - 'Protocol': 'docs/apidocs_aliecs.md'
        - 'coconut':
            - 'Overview': 'coconut/README.md'
            - 'Command Ref.': 'coconut/doc/coconut.md'
        - 'apricot':
            - 'Overview': 'apricot/README.md'
            - 'HTTP Service': 'apricot/docs/apricot_http_service.md'
            - 'Protocol': 'docs/apidocs_apricot.md'
            - 'Command Ref.': 'apricot/docs/apricot.md'
        - 'occ':
            - 'Overview': 'occ/README.md'
            - 'Example': 'occ/occlib/examples/dummy-process/README.md'
            - 'Protocol': 'docs/apidocs_occ.md'
        - 'peanut':
            - 'Overview': 'occ/peanut/README.md'
        - 'Event Service': 'docs/kafka.md'
