chans:
  buildertosender:
    numSockets: 1
    0:
      address: ipc://@o2ipc-d6qto8m8ndm409ltqnh0
      method: connect
      rateLogging: 0
      rcvBufSize: 1000
      rcvKernelSize: 0
      sndBufSize: 1000
      sndKernelSize: 0
      transport: shmem
      type: pull

environment_id: 31UAUL4cwuk
