//
// === This file is part of ALICE O² ===
//
// Copyright 2024 CERN and copyright holders of ALICE O².
// Author: Teo Mrnjavac <teo.mrnjavac@cern.ch>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
// In applying this license CERN does not waive the privileges and
// immunities granted to it by virtue of its status as an
// Intergovernmental Organization or submit itself to any jurisdiction.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: protos/events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ev_MetaEvent_MesosHeartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ev_MetaEvent_MesosHeartbeat) Reset() {
	*x = Ev_MetaEvent_MesosHeartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ev_MetaEvent_MesosHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ev_MetaEvent_MesosHeartbeat) ProtoMessage() {}

func (x *Ev_MetaEvent_MesosHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_protos_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ev_MetaEvent_MesosHeartbeat.ProtoReflect.Descriptor instead.
func (*Ev_MetaEvent_MesosHeartbeat) Descriptor() ([]byte, []int) {
	return file_protos_events_proto_rawDescGZIP(), []int{0}
}

type Ev_MetaEvent_FrameworkFailure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Ev_MetaEvent_FrameworkFailure) Reset() {
	*x = Ev_MetaEvent_FrameworkFailure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ev_MetaEvent_FrameworkFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ev_MetaEvent_FrameworkFailure) ProtoMessage() {}

func (x *Ev_MetaEvent_FrameworkFailure) ProtoReflect() protoreflect.Message {
	mi := &file_protos_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ev_MetaEvent_FrameworkFailure.ProtoReflect.Descriptor instead.
func (*Ev_MetaEvent_FrameworkFailure) Descriptor() ([]byte, []int) {
	return file_protos_events_proto_rawDescGZIP(), []int{1}
}

func (x *Ev_MetaEvent_FrameworkFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Ev_EnvironmentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvironmentId    string `protobuf:"bytes,1,opt,name=environmentId,proto3" json:"environmentId,omitempty"`
	State            string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	CurrentRunNumber uint32 `protobuf:"varint,3,opt,name=currentRunNumber,proto3" json:"currentRunNumber,omitempty"`
	Error            string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Message          string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Transition       string `protobuf:"bytes,6,opt,name=transition,proto3" json:"transition,omitempty"`
	TransitionStep   string `protobuf:"bytes,7,opt,name=transitionStep,proto3" json:"transitionStep,omitempty"`
}

func (x *Ev_EnvironmentEvent) Reset() {
	*x = Ev_EnvironmentEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ev_EnvironmentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ev_EnvironmentEvent) ProtoMessage() {}

func (x *Ev_EnvironmentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ev_EnvironmentEvent.ProtoReflect.Descriptor instead.
func (*Ev_EnvironmentEvent) Descriptor() ([]byte, []int) {
	return file_protos_events_proto_rawDescGZIP(), []int{2}
}

func (x *Ev_EnvironmentEvent) GetEnvironmentId() string {
	if x != nil {
		return x.EnvironmentId
	}
	return ""
}

func (x *Ev_EnvironmentEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Ev_EnvironmentEvent) GetCurrentRunNumber() uint32 {
	if x != nil {
		return x.CurrentRunNumber
	}
	return 0
}

func (x *Ev_EnvironmentEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Ev_EnvironmentEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Ev_EnvironmentEvent) GetTransition() string {
	if x != nil {
		return x.Transition
	}
	return ""
}

func (x *Ev_EnvironmentEvent) GetTransitionStep() string {
	if x != nil {
		return x.TransitionStep
	}
	return ""
}

type Ev_TaskEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Taskid    string `protobuf:"bytes,2,opt,name=taskid,proto3" json:"taskid,omitempty"`
	State     string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Status    string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Hostname  string `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ClassName string `protobuf:"bytes,6,opt,name=className,proto3" json:"className,omitempty"`
}

func (x *Ev_TaskEvent) Reset() {
	*x = Ev_TaskEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ev_TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ev_TaskEvent) ProtoMessage() {}

func (x *Ev_TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ev_TaskEvent.ProtoReflect.Descriptor instead.
func (*Ev_TaskEvent) Descriptor() ([]byte, []int) {
	return file_protos_events_proto_rawDescGZIP(), []int{3}
}

func (x *Ev_TaskEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ev_TaskEvent) GetTaskid() string {
	if x != nil {
		return x.Taskid
	}
	return ""
}

func (x *Ev_TaskEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Ev_TaskEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ev_TaskEvent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Ev_TaskEvent) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type Ev_RoleEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status   string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	State    string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	RolePath string `protobuf:"bytes,4,opt,name=rolePath,proto3" json:"rolePath,omitempty"`
}

func (x *Ev_RoleEvent) Reset() {
	*x = Ev_RoleEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ev_RoleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ev_RoleEvent) ProtoMessage() {}

func (x *Ev_RoleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protos_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ev_RoleEvent.ProtoReflect.Descriptor instead.
func (*Ev_RoleEvent) Descriptor() ([]byte, []int) {
	return file_protos_events_proto_rawDescGZIP(), []int{4}
}

func (x *Ev_RoleEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ev_RoleEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Ev_RoleEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Ev_RoleEvent) GetRolePath() string {
	if x != nil {
		return x.RolePath
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are assignable to Payload:
	//
	//	*Event_EnvironmentEvent
	//	*Event_TaskEvent
	//	*Event_RoleEvent
	//	*Event_FrameworkFailureEvent
	//	*Event_MesosHeartbeatEvent
	Payload isEvent_Payload `protobuf_oneof:"Payload"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_protos_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_protos_events_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (m *Event) GetPayload() isEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Event) GetEnvironmentEvent() *Ev_EnvironmentEvent {
	if x, ok := x.GetPayload().(*Event_EnvironmentEvent); ok {
		return x.EnvironmentEvent
	}
	return nil
}

func (x *Event) GetTaskEvent() *Ev_TaskEvent {
	if x, ok := x.GetPayload().(*Event_TaskEvent); ok {
		return x.TaskEvent
	}
	return nil
}

func (x *Event) GetRoleEvent() *Ev_RoleEvent {
	if x, ok := x.GetPayload().(*Event_RoleEvent); ok {
		return x.RoleEvent
	}
	return nil
}

func (x *Event) GetFrameworkFailureEvent() *Ev_MetaEvent_FrameworkFailure {
	if x, ok := x.GetPayload().(*Event_FrameworkFailureEvent); ok {
		return x.FrameworkFailureEvent
	}
	return nil
}

func (x *Event) GetMesosHeartbeatEvent() *Ev_MetaEvent_MesosHeartbeat {
	if x, ok := x.GetPayload().(*Event_MesosHeartbeatEvent); ok {
		return x.MesosHeartbeatEvent
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_EnvironmentEvent struct {
	EnvironmentEvent *Ev_EnvironmentEvent `protobuf:"bytes,2,opt,name=environmentEvent,proto3,oneof"`
}

type Event_TaskEvent struct {
	TaskEvent *Ev_TaskEvent `protobuf:"bytes,3,opt,name=taskEvent,proto3,oneof"`
}

type Event_RoleEvent struct {
	RoleEvent *Ev_RoleEvent `protobuf:"bytes,4,opt,name=roleEvent,proto3,oneof"`
}

type Event_FrameworkFailureEvent struct {
	FrameworkFailureEvent *Ev_MetaEvent_FrameworkFailure `protobuf:"bytes,5,opt,name=frameworkFailureEvent,proto3,oneof"`
}

type Event_MesosHeartbeatEvent struct {
	MesosHeartbeatEvent *Ev_MetaEvent_MesosHeartbeat `protobuf:"bytes,6,opt,name=mesosHeartbeatEvent,proto3,oneof"`
}

func (*Event_EnvironmentEvent) isEvent_Payload() {}

func (*Event_TaskEvent) isEvent_Payload() {}

func (*Event_RoleEvent) isEvent_Payload() {}

func (*Event_FrameworkFailureEvent) isEvent_Payload() {}

func (*Event_MesosHeartbeatEvent) isEvent_Payload() {}

var File_protos_events_proto protoreflect.FileDescriptor

var file_protos_events_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x1d, 0x0a,
	0x1b, 0x45, 0x76, 0x5f, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x4d, 0x65,
	0x73, 0x6f, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x22, 0x39, 0x0a, 0x1d,
	0x45, 0x76, 0x5f, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x46, 0x72, 0x61,
	0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xf5, 0x01, 0x0a, 0x13, 0x45, 0x76, 0x5f, 0x45,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x24, 0x0a, 0x0d, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x10, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x75, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x75,
	0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x65, 0x70, 0x22,
	0xa2, 0x01, 0x0a, 0x0c, 0x45, 0x76, 0x5f, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6c, 0x0a, 0x0c, 0x45, 0x76, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x22, 0x9f, 0x03, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x49, 0x0a, 0x10, 0x65, 0x6e,
	0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x45, 0x76,
	0x5f, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x48, 0x00, 0x52, 0x10, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x45, 0x76, 0x5f, 0x54, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x09, 0x72,
	0x6f, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x45, 0x76, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x5d, 0x0a, 0x15, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x46, 0x61,
	0x69, 0x6c, 0x75, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x45, 0x76, 0x5f, 0x4d, 0x65, 0x74,
	0x61, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b,
	0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x48, 0x00, 0x52, 0x15, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x77, 0x6f, 0x72, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x57, 0x0a, 0x13, 0x6d, 0x65, 0x73, 0x6f, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x45, 0x76, 0x5f, 0x4d, 0x65, 0x74, 0x61, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x4d, 0x65, 0x73, 0x6f, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x48, 0x00, 0x52, 0x13, 0x6d, 0x65, 0x73, 0x6f, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x42, 0x53, 0x0a, 0x1f, 0x63, 0x68, 0x2e, 0x63, 0x65, 0x72, 0x6e, 0x2e,
	0x61, 0x6c, 0x69, 0x63, 0x65, 0x2e, 0x6f, 0x32, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x69, 0x63, 0x65, 0x4f, 0x32, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_events_proto_rawDescOnce sync.Once
	file_protos_events_proto_rawDescData = file_protos_events_proto_rawDesc
)

func file_protos_events_proto_rawDescGZIP() []byte {
	file_protos_events_proto_rawDescOnce.Do(func() {
		file_protos_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_events_proto_rawDescData)
	})
	return file_protos_events_proto_rawDescData
}

var file_protos_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protos_events_proto_goTypes = []interface{}{
	(*Ev_MetaEvent_MesosHeartbeat)(nil),   // 0: events.Ev_MetaEvent_MesosHeartbeat
	(*Ev_MetaEvent_FrameworkFailure)(nil), // 1: events.Ev_MetaEvent_FrameworkFailure
	(*Ev_EnvironmentEvent)(nil),           // 2: events.Ev_EnvironmentEvent
	(*Ev_TaskEvent)(nil),                  // 3: events.Ev_TaskEvent
	(*Ev_RoleEvent)(nil),                  // 4: events.Ev_RoleEvent
	(*Event)(nil),                         // 5: events.Event
}
var file_protos_events_proto_depIdxs = []int32{
	2, // 0: events.Event.environmentEvent:type_name -> events.Ev_EnvironmentEvent
	3, // 1: events.Event.taskEvent:type_name -> events.Ev_TaskEvent
	4, // 2: events.Event.roleEvent:type_name -> events.Ev_RoleEvent
	1, // 3: events.Event.frameworkFailureEvent:type_name -> events.Ev_MetaEvent_FrameworkFailure
	0, // 4: events.Event.mesosHeartbeatEvent:type_name -> events.Ev_MetaEvent_MesosHeartbeat
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protos_events_proto_init() }
func file_protos_events_proto_init() {
	if File_protos_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ev_MetaEvent_MesosHeartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ev_MetaEvent_FrameworkFailure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ev_EnvironmentEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ev_TaskEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ev_RoleEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_events_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Event_EnvironmentEvent)(nil),
		(*Event_TaskEvent)(nil),
		(*Event_RoleEvent)(nil),
		(*Event_FrameworkFailureEvent)(nil),
		(*Event_MesosHeartbeatEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_events_proto_goTypes,
		DependencyIndexes: file_protos_events_proto_depIdxs,
		MessageInfos:      file_protos_events_proto_msgTypes,
	}.Build()
	File_protos_events_proto = out.File
	file_protos_events_proto_rawDesc = nil
	file_protos_events_proto_goTypes = nil
	file_protos_events_proto_depIdxs = nil
}
