externalDocs:
  description: AliECS handbook
  url: https://alice-flp.docs.cern.ch/aliecs/handbook/
info:
  contact:
    email: alice-o2-flp-support@cern.ch
    name: O² FLP support
    url: https://alice-flp.docs.cern.ch/
  description: REST API for ALICE O² Apricot configuration service
  title: O² Apricot REST API
  version: "1.0"
paths:
  /components:
    get:
      description: Returns a list of all configuration components managed by Apricot
      parameters:
      - default: text
        description: Output format, json or text
        enum:
        - json
        - text
        in: query
        name: format
        type: string
      produces:
      - application/json
      - text/plain
      responses:
        "200":
          description: List of components, either as JSON array or comma-separated
            plain text
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: List Apricot-managed configuration components
      tags:
      - component configuration
  /components/_invalidate_cache:
    post:
      description: Invalidates all cached templates for all configuration components
        managed by Apricot
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      summary: Clear cache of Apricot-managed configuration component templates
      tags:
      - component configuration
  /components/{component}:
    get:
      description: Returns a list of all entries belonging to a given configuration
        component corresponding to the given query. The component must be provided.
        If the run type is not provided, entries for all run types are returned. If
        the role name is not provided, entries for all role names are returned. If
        the raw flag is true, AApricot will not attempt to include "ANY"/"any" run
        types or role names, and will return only the entries stored under the provided
        Consul path. If the raw flag is false, Apricot will include all entries for
        the given component, run type and role name, including entries stored under
        "ANY" and "any" paths corresponding to fallback values valid for all run types
        or role names.
      parameters:
      - default: text
        description: Output format, json or text
        enum:
        - json
        - text
        in: query
        name: format
        type: string
      - default: false
        description: If true, the query returns strictly Consul paths without catching
          all run types or role names with ANY/any
        in: query
        name: raw
        type: boolean
      - description: Configuration component
        in: path
        name: component
        required: true
        type: string
      produces:
      - application/json
      - text/plain
      responses:
        "200":
          description: List of entries, either as JSON array or comma-separated plain
            text
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad request, if the run type is invalid
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Lists all entries for an Apricot-managed configuration component
      tags:
      - component configuration
  /components/{component}/{runtype}:
    get:
      description: Returns a list of all entries belonging to a given configuration
        component corresponding to the given query. The component must be provided.
        If the run type is not provided, entries for all run types are returned. If
        the role name is not provided, entries for all role names are returned. If
        the raw flag is true, AApricot will not attempt to include "ANY"/"any" run
        types or role names, and will return only the entries stored under the provided
        Consul path. If the raw flag is false, Apricot will include all entries for
        the given component, run type and role name, including entries stored under
        "ANY" and "any" paths corresponding to fallback values valid for all run types
        or role names.
      parameters:
      - default: text
        description: Output format, json or text
        enum:
        - json
        - text
        in: query
        name: format
        type: string
      - default: false
        description: If true, the query returns strictly Consul paths without catching
          all run types or role names with ANY/any
        in: query
        name: raw
        type: boolean
      - description: Configuration component
        in: path
        name: component
        required: true
        type: string
      - default: ANY
        description: O² Run type, must be capitalized
        in: path
        name: runtype
        type: string
      produces:
      - application/json
      - text/plain
      responses:
        "200":
          description: List of entries, either as JSON array or comma-separated plain
            text
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad request, if the run type is invalid
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Lists all entries for an Apricot-managed configuration component
      tags:
      - component configuration
  /components/{component}/{runtype}/{rolename}:
    get:
      description: Returns a list of all entries belonging to a given configuration
        component corresponding to the given query. The component must be provided.
        If the run type is not provided, entries for all run types are returned. If
        the role name is not provided, entries for all role names are returned. If
        the raw flag is true, AApricot will not attempt to include "ANY"/"any" run
        types or role names, and will return only the entries stored under the provided
        Consul path. If the raw flag is false, Apricot will include all entries for
        the given component, run type and role name, including entries stored under
        "ANY" and "any" paths corresponding to fallback values valid for all run types
        or role names.
      parameters:
      - default: text
        description: Output format, json or text
        enum:
        - json
        - text
        in: query
        name: format
        type: string
      - default: false
        description: If true, the query returns strictly Consul paths without catching
          all run types or role names with ANY/any
        in: query
        name: raw
        type: boolean
      - description: Configuration component
        in: path
        name: component
        required: true
        type: string
      - default: ANY
        description: O² Run type, must be capitalized
        in: path
        name: runtype
        type: string
      - default: any
        description: Role name
        in: path
        name: rolename
        type: string
      produces:
      - application/json
      - text/plain
      responses:
        "200":
          description: List of entries, either as JSON array or comma-separated plain
            text
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad request, if the run type is invalid
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Lists all entries for an Apricot-managed configuration component
      tags:
      - component configuration
  /components/{component}/{runtype}/{rolename}/{entry}:
    get:
      description: The provided component, run type, role name and entry key are used
        to query the configuration service for a configuration entry, which is then
        processed in the O² Apricot template system to produce the final payload,
        and returned as string..
      parameters:
      - default: false
        description: If true, template processing is performed to produce the final
          payload; if false, the entry is returned verbatim. In the true case, any
          number of additional string key-value pairs may be passed as query parameters
          (e.g. ?process=true&mykey1=myvalue1&mykey2=myvalue2), which are then fed
          into the template system as variables that affect configuration payload
          generation
        in: query
        name: process
        type: boolean
      - description: Configuration component
        in: path
        name: component
        required: true
        type: string
      - description: O² Run type, must be capitalized
        in: path
        name: runtype
        required: true
        type: string
      - description: Role name
        in: path
        name: rolename
        required: true
        type: string
      - description: Entry key
        in: path
        name: entry
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Configuration payload for the queried entry, either processed
            or verbatim depending on the process flag
          schema:
            type: string
        "400":
          description: Bad request, if a parameter is invalid
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Returns a configuration payload for a given component, run type, role
        name and entry key
      tags:
      - component configuration
  /components/{component}/{runtype}/{rolename}/{entry}/resolve:
    get:
      description: Returns a resolved path for a given component, run type, role name
        and entry key. The path points to an actual existing entry in Consul, resolving
        ANY run type and any rolename wildcards.
      parameters:
      - description: Configuration component
        in: path
        name: component
        required: true
        type: string
      - description: O² Run type, must be capitalized
        in: path
        name: runtype
        required: true
        type: string
      - description: Role name
        in: path
        name: rolename
        required: true
        type: string
      - description: Entry key
        in: path
        name: entry
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Resolved path for the queried entry
          schema:
            type: string
        "400":
          description: Bad request, if a parameter is invalid
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Resolves a query for a given component, run type, role name and entry
        key
      tags:
      - component configuration
  /inventory/detectors/{detector}/flps/{format}:
    get:
      description: Returns the list of all Apricot-managed hosts in the cluster that
        are known to be FLPs and serving the given detector, newline-separated or
        JSON depending on the format parameter
      parameters:
      - default: text
        description: Output format, json or text
        enum:
        - json
        - text
        in: path
        name: format
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: List of FLPs in the cluster known to Apricot, newline-separated
            or JSON depending on the format parameter
          schema:
            type: string
      summary: Returns the list of FLPs in the cluster that serve a given detector
      tags:
      - cluster inventory
  /inventory/detectors/{format}:
    get:
      description: Returns the list of all detectors known to Apricot that belong
        to the installed instance, newline-separated or JSON depending on the format
        parameter
      parameters:
      - default: text
        description: Output format, json or text
        enum:
        - json
        - text
        in: path
        name: format
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: List of detectors in the instance known to Apricot, newline-separated
            or JSON depending on the format parameter
          schema:
            type: string
      summary: Returns the list of detectors belonging to the installed instance known
        to Apricot
      tags:
      - cluster inventory
  /inventory/flps/{format}:
    get:
      description: Returns the list of all Apricot-managed hosts in the cluster that
        are known to be FLPs, newline-separated or JSON depending on the format parameter
      parameters:
      - default: text
        description: Output format, json or text
        enum:
        - json
        - text
        in: path
        name: format
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: List of FLPs in the cluster known to Apricot, newline-separated
            or JSON depending on the format parameter
          schema:
            type: string
      summary: Returns the list of FLPs in the cluster known to Apricot
      tags:
      - cluster inventory
swagger: "2.0"
