// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/octlserver.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	protos/octlserver.proto

It has these top-level messages:
	Event_MesosHeartbeat
	StatusRequest
	StatusReply
	StatusUpdate
	GetFrameworkInfoRequest
	GetFrameworkInfoReply
	TeardownRequest
	TeardownReply
	GetEnvironmentsRequest
	GetEnvironmentsReply
	EnvironmentInfo
	NewEnvironmentRequest
	NewEnvironmentReply
	GetEnvironmentRequest
	GetEnvironmentReply
	ControlEnvironmentRequest
	ControlEnvironmentReply
	ModifyEnvironmentRequest
	EnvironmentOperation
	ModifyEnvironmentReply
	DestroyEnvironmentRequest
	DestroyEnvironmentReply
	GetRolesRequest
	GetRolesReply
	RoleInfo
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusUpdate_Level int32

const (
	StatusUpdate_DEBUG   StatusUpdate_Level = 0
	StatusUpdate_INFO    StatusUpdate_Level = 1
	StatusUpdate_WARNING StatusUpdate_Level = 2
	StatusUpdate_ERROR   StatusUpdate_Level = 3
)

var StatusUpdate_Level_name = map[int32]string{
	0: "DEBUG",
	1: "INFO",
	2: "WARNING",
	3: "ERROR",
}
var StatusUpdate_Level_value = map[string]int32{
	"DEBUG":   0,
	"INFO":    1,
	"WARNING": 2,
	"ERROR":   3,
}

func (x StatusUpdate_Level) String() string {
	return proto.EnumName(StatusUpdate_Level_name, int32(x))
}
func (StatusUpdate_Level) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type ControlEnvironmentRequest_Optype int32

const (
	ControlEnvironmentRequest_NOOP              ControlEnvironmentRequest_Optype = 0
	ControlEnvironmentRequest_START_ENVIRONMENT ControlEnvironmentRequest_Optype = 1
	ControlEnvironmentRequest_STOP_ENVIRONMENT  ControlEnvironmentRequest_Optype = 2
	ControlEnvironmentRequest_CONFIGURE         ControlEnvironmentRequest_Optype = 3
)

var ControlEnvironmentRequest_Optype_name = map[int32]string{
	0: "NOOP",
	1: "START_ENVIRONMENT",
	2: "STOP_ENVIRONMENT",
	3: "CONFIGURE",
}
var ControlEnvironmentRequest_Optype_value = map[string]int32{
	"NOOP":              0,
	"START_ENVIRONMENT": 1,
	"STOP_ENVIRONMENT":  2,
	"CONFIGURE":         3,
}

func (x ControlEnvironmentRequest_Optype) String() string {
	return proto.EnumName(ControlEnvironmentRequest_Optype_name, int32(x))
}
func (ControlEnvironmentRequest_Optype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15, 0}
}

type EnvironmentOperation_Optype int32

const (
	EnvironmentOperation_NOOP        EnvironmentOperation_Optype = 0
	EnvironmentOperation_REMOVE_ROLE EnvironmentOperation_Optype = 3
	EnvironmentOperation_ADD_ROLE    EnvironmentOperation_Optype = 4
)

var EnvironmentOperation_Optype_name = map[int32]string{
	0: "NOOP",
	3: "REMOVE_ROLE",
	4: "ADD_ROLE",
}
var EnvironmentOperation_Optype_value = map[string]int32{
	"NOOP":        0,
	"REMOVE_ROLE": 3,
	"ADD_ROLE":    4,
}

func (x EnvironmentOperation_Optype) String() string {
	return proto.EnumName(EnvironmentOperation_Optype_name, int32(x))
}
func (EnvironmentOperation_Optype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18, 0}
}

type Event_MesosHeartbeat struct {
}

func (m *Event_MesosHeartbeat) Reset()                    { *m = Event_MesosHeartbeat{} }
func (m *Event_MesosHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*Event_MesosHeartbeat) ProtoMessage()               {}
func (*Event_MesosHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StatusReply struct {
	State         string          `protobuf:"bytes,1,opt,name=state" json:"state,omitempty"`
	StatusUpdates []*StatusUpdate `protobuf:"bytes,2,rep,name=statusUpdates" json:"statusUpdates,omitempty"`
}

func (m *StatusReply) Reset()                    { *m = StatusReply{} }
func (m *StatusReply) String() string            { return proto.CompactTextString(m) }
func (*StatusReply) ProtoMessage()               {}
func (*StatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StatusReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *StatusReply) GetStatusUpdates() []*StatusUpdate {
	if m != nil {
		return m.StatusUpdates
	}
	return nil
}

type StatusUpdate struct {
	Level StatusUpdate_Level `protobuf:"varint,1,opt,name=level,enum=octl.StatusUpdate_Level" json:"level,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*StatusUpdate_MesosHeartbeat
	Event isStatusUpdate_Event `protobuf_oneof:"Event"`
}

func (m *StatusUpdate) Reset()                    { *m = StatusUpdate{} }
func (m *StatusUpdate) String() string            { return proto.CompactTextString(m) }
func (*StatusUpdate) ProtoMessage()               {}
func (*StatusUpdate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isStatusUpdate_Event interface {
	isStatusUpdate_Event()
}

type StatusUpdate_MesosHeartbeat struct {
	MesosHeartbeat *Event_MesosHeartbeat `protobuf:"bytes,2,opt,name=mesosHeartbeat,oneof"`
}

func (*StatusUpdate_MesosHeartbeat) isStatusUpdate_Event() {}

func (m *StatusUpdate) GetEvent() isStatusUpdate_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StatusUpdate) GetLevel() StatusUpdate_Level {
	if m != nil {
		return m.Level
	}
	return StatusUpdate_DEBUG
}

func (m *StatusUpdate) GetMesosHeartbeat() *Event_MesosHeartbeat {
	if x, ok := m.GetEvent().(*StatusUpdate_MesosHeartbeat); ok {
		return x.MesosHeartbeat
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StatusUpdate) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StatusUpdate_OneofMarshaler, _StatusUpdate_OneofUnmarshaler, _StatusUpdate_OneofSizer, []interface{}{
		(*StatusUpdate_MesosHeartbeat)(nil),
	}
}

func _StatusUpdate_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StatusUpdate)
	// Event
	switch x := m.Event.(type) {
	case *StatusUpdate_MesosHeartbeat:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MesosHeartbeat); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StatusUpdate.Event has unexpected type %T", x)
	}
	return nil
}

func _StatusUpdate_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StatusUpdate)
	switch tag {
	case 2: // Event.mesosHeartbeat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Event_MesosHeartbeat)
		err := b.DecodeMessage(msg)
		m.Event = &StatusUpdate_MesosHeartbeat{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StatusUpdate_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StatusUpdate)
	// Event
	switch x := m.Event.(type) {
	case *StatusUpdate_MesosHeartbeat:
		s := proto.Size(x.MesosHeartbeat)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetFrameworkInfoRequest struct {
}

func (m *GetFrameworkInfoRequest) Reset()                    { *m = GetFrameworkInfoRequest{} }
func (m *GetFrameworkInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFrameworkInfoRequest) ProtoMessage()               {}
func (*GetFrameworkInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetFrameworkInfoReply struct {
	FrameworkId       string `protobuf:"bytes,1,opt,name=frameworkId" json:"frameworkId,omitempty"`
	EnvironmentsCount int32  `protobuf:"varint,2,opt,name=environmentsCount" json:"environmentsCount,omitempty"`
	RolesCount        int32  `protobuf:"varint,3,opt,name=rolesCount" json:"rolesCount,omitempty"`
	State             string `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
}

func (m *GetFrameworkInfoReply) Reset()                    { *m = GetFrameworkInfoReply{} }
func (m *GetFrameworkInfoReply) String() string            { return proto.CompactTextString(m) }
func (*GetFrameworkInfoReply) ProtoMessage()               {}
func (*GetFrameworkInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetFrameworkInfoReply) GetFrameworkId() string {
	if m != nil {
		return m.FrameworkId
	}
	return ""
}

func (m *GetFrameworkInfoReply) GetEnvironmentsCount() int32 {
	if m != nil {
		return m.EnvironmentsCount
	}
	return 0
}

func (m *GetFrameworkInfoReply) GetRolesCount() int32 {
	if m != nil {
		return m.RolesCount
	}
	return 0
}

func (m *GetFrameworkInfoReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type TeardownRequest struct {
	Reason string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
}

func (m *TeardownRequest) Reset()                    { *m = TeardownRequest{} }
func (m *TeardownRequest) String() string            { return proto.CompactTextString(m) }
func (*TeardownRequest) ProtoMessage()               {}
func (*TeardownRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *TeardownRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type TeardownReply struct {
}

func (m *TeardownReply) Reset()                    { *m = TeardownReply{} }
func (m *TeardownReply) String() string            { return proto.CompactTextString(m) }
func (*TeardownReply) ProtoMessage()               {}
func (*TeardownReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetEnvironmentsRequest struct {
}

func (m *GetEnvironmentsRequest) Reset()                    { *m = GetEnvironmentsRequest{} }
func (m *GetEnvironmentsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEnvironmentsRequest) ProtoMessage()               {}
func (*GetEnvironmentsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type GetEnvironmentsReply struct {
	FrameworkId  string             `protobuf:"bytes,1,opt,name=frameworkId" json:"frameworkId,omitempty"`
	Environments []*EnvironmentInfo `protobuf:"bytes,2,rep,name=environments" json:"environments,omitempty"`
}

func (m *GetEnvironmentsReply) Reset()                    { *m = GetEnvironmentsReply{} }
func (m *GetEnvironmentsReply) String() string            { return proto.CompactTextString(m) }
func (*GetEnvironmentsReply) ProtoMessage()               {}
func (*GetEnvironmentsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetEnvironmentsReply) GetFrameworkId() string {
	if m != nil {
		return m.FrameworkId
	}
	return ""
}

func (m *GetEnvironmentsReply) GetEnvironments() []*EnvironmentInfo {
	if m != nil {
		return m.Environments
	}
	return nil
}

type EnvironmentInfo struct {
	Id          string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	CreatedWhen string   `protobuf:"bytes,2,opt,name=createdWhen" json:"createdWhen,omitempty"`
	State       string   `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	Roles       []string `protobuf:"bytes,4,rep,name=roles" json:"roles,omitempty"`
}

func (m *EnvironmentInfo) Reset()                    { *m = EnvironmentInfo{} }
func (m *EnvironmentInfo) String() string            { return proto.CompactTextString(m) }
func (*EnvironmentInfo) ProtoMessage()               {}
func (*EnvironmentInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EnvironmentInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EnvironmentInfo) GetCreatedWhen() string {
	if m != nil {
		return m.CreatedWhen
	}
	return ""
}

func (m *EnvironmentInfo) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *EnvironmentInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type NewEnvironmentRequest struct {
	Roles []string `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (m *NewEnvironmentRequest) Reset()                    { *m = NewEnvironmentRequest{} }
func (m *NewEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*NewEnvironmentRequest) ProtoMessage()               {}
func (*NewEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *NewEnvironmentRequest) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type NewEnvironmentReply struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	State string `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
}

func (m *NewEnvironmentReply) Reset()                    { *m = NewEnvironmentReply{} }
func (m *NewEnvironmentReply) String() string            { return proto.CompactTextString(m) }
func (*NewEnvironmentReply) ProtoMessage()               {}
func (*NewEnvironmentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *NewEnvironmentReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewEnvironmentReply) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type GetEnvironmentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetEnvironmentRequest) Reset()                    { *m = GetEnvironmentRequest{} }
func (m *GetEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEnvironmentRequest) ProtoMessage()               {}
func (*GetEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetEnvironmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetEnvironmentReply struct {
	Environment *EnvironmentInfo `protobuf:"bytes,1,opt,name=environment" json:"environment,omitempty"`
}

func (m *GetEnvironmentReply) Reset()                    { *m = GetEnvironmentReply{} }
func (m *GetEnvironmentReply) String() string            { return proto.CompactTextString(m) }
func (*GetEnvironmentReply) ProtoMessage()               {}
func (*GetEnvironmentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetEnvironmentReply) GetEnvironment() *EnvironmentInfo {
	if m != nil {
		return m.Environment
	}
	return nil
}

type ControlEnvironmentRequest struct {
	Id   string                           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type ControlEnvironmentRequest_Optype `protobuf:"varint,2,opt,name=type,enum=octl.ControlEnvironmentRequest_Optype" json:"type,omitempty"`
}

func (m *ControlEnvironmentRequest) Reset()                    { *m = ControlEnvironmentRequest{} }
func (m *ControlEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*ControlEnvironmentRequest) ProtoMessage()               {}
func (*ControlEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ControlEnvironmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ControlEnvironmentRequest) GetType() ControlEnvironmentRequest_Optype {
	if m != nil {
		return m.Type
	}
	return ControlEnvironmentRequest_NOOP
}

type ControlEnvironmentReply struct {
}

func (m *ControlEnvironmentReply) Reset()                    { *m = ControlEnvironmentReply{} }
func (m *ControlEnvironmentReply) String() string            { return proto.CompactTextString(m) }
func (*ControlEnvironmentReply) ProtoMessage()               {}
func (*ControlEnvironmentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type ModifyEnvironmentRequest struct {
	Id         string                  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Operations []*EnvironmentOperation `protobuf:"bytes,2,rep,name=operations" json:"operations,omitempty"`
}

func (m *ModifyEnvironmentRequest) Reset()                    { *m = ModifyEnvironmentRequest{} }
func (m *ModifyEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*ModifyEnvironmentRequest) ProtoMessage()               {}
func (*ModifyEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ModifyEnvironmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ModifyEnvironmentRequest) GetOperations() []*EnvironmentOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

type EnvironmentOperation struct {
	Type     EnvironmentOperation_Optype `protobuf:"varint,1,opt,name=type,enum=octl.EnvironmentOperation_Optype" json:"type,omitempty"`
	RoleName string                      `protobuf:"bytes,2,opt,name=roleName" json:"roleName,omitempty"`
}

func (m *EnvironmentOperation) Reset()                    { *m = EnvironmentOperation{} }
func (m *EnvironmentOperation) String() string            { return proto.CompactTextString(m) }
func (*EnvironmentOperation) ProtoMessage()               {}
func (*EnvironmentOperation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *EnvironmentOperation) GetType() EnvironmentOperation_Optype {
	if m != nil {
		return m.Type
	}
	return EnvironmentOperation_NOOP
}

func (m *EnvironmentOperation) GetRoleName() string {
	if m != nil {
		return m.RoleName
	}
	return ""
}

type ModifyEnvironmentReply struct {
	FailedOperations []*EnvironmentOperation `protobuf:"bytes,1,rep,name=failedOperations" json:"failedOperations,omitempty"`
}

func (m *ModifyEnvironmentReply) Reset()                    { *m = ModifyEnvironmentReply{} }
func (m *ModifyEnvironmentReply) String() string            { return proto.CompactTextString(m) }
func (*ModifyEnvironmentReply) ProtoMessage()               {}
func (*ModifyEnvironmentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ModifyEnvironmentReply) GetFailedOperations() []*EnvironmentOperation {
	if m != nil {
		return m.FailedOperations
	}
	return nil
}

type DestroyEnvironmentRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DestroyEnvironmentRequest) Reset()                    { *m = DestroyEnvironmentRequest{} }
func (m *DestroyEnvironmentRequest) String() string            { return proto.CompactTextString(m) }
func (*DestroyEnvironmentRequest) ProtoMessage()               {}
func (*DestroyEnvironmentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DestroyEnvironmentRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DestroyEnvironmentReply struct {
}

func (m *DestroyEnvironmentReply) Reset()                    { *m = DestroyEnvironmentReply{} }
func (m *DestroyEnvironmentReply) String() string            { return proto.CompactTextString(m) }
func (*DestroyEnvironmentReply) ProtoMessage()               {}
func (*DestroyEnvironmentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type GetRolesRequest struct {
}

func (m *GetRolesRequest) Reset()                    { *m = GetRolesRequest{} }
func (m *GetRolesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRolesRequest) ProtoMessage()               {}
func (*GetRolesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

type GetRolesReply struct {
	Roles []*RoleInfo `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (m *GetRolesReply) Reset()                    { *m = GetRolesReply{} }
func (m *GetRolesReply) String() string            { return proto.CompactTextString(m) }
func (*GetRolesReply) ProtoMessage()               {}
func (*GetRolesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *GetRolesReply) GetRoles() []*RoleInfo {
	if m != nil {
		return m.Roles
	}
	return nil
}

type RoleInfo struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Locked   bool   `protobuf:"varint,2,opt,name=locked" json:"locked,omitempty"`
	Hostname string `protobuf:"bytes,3,opt,name=hostname" json:"hostname,omitempty"`
}

func (m *RoleInfo) Reset()                    { *m = RoleInfo{} }
func (m *RoleInfo) String() string            { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()               {}
func (*RoleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *RoleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoleInfo) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

func (m *RoleInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func init() {
	proto.RegisterType((*Event_MesosHeartbeat)(nil), "octl.Event_MesosHeartbeat")
	proto.RegisterType((*StatusRequest)(nil), "octl.StatusRequest")
	proto.RegisterType((*StatusReply)(nil), "octl.StatusReply")
	proto.RegisterType((*StatusUpdate)(nil), "octl.StatusUpdate")
	proto.RegisterType((*GetFrameworkInfoRequest)(nil), "octl.GetFrameworkInfoRequest")
	proto.RegisterType((*GetFrameworkInfoReply)(nil), "octl.GetFrameworkInfoReply")
	proto.RegisterType((*TeardownRequest)(nil), "octl.TeardownRequest")
	proto.RegisterType((*TeardownReply)(nil), "octl.TeardownReply")
	proto.RegisterType((*GetEnvironmentsRequest)(nil), "octl.GetEnvironmentsRequest")
	proto.RegisterType((*GetEnvironmentsReply)(nil), "octl.GetEnvironmentsReply")
	proto.RegisterType((*EnvironmentInfo)(nil), "octl.EnvironmentInfo")
	proto.RegisterType((*NewEnvironmentRequest)(nil), "octl.NewEnvironmentRequest")
	proto.RegisterType((*NewEnvironmentReply)(nil), "octl.NewEnvironmentReply")
	proto.RegisterType((*GetEnvironmentRequest)(nil), "octl.GetEnvironmentRequest")
	proto.RegisterType((*GetEnvironmentReply)(nil), "octl.GetEnvironmentReply")
	proto.RegisterType((*ControlEnvironmentRequest)(nil), "octl.ControlEnvironmentRequest")
	proto.RegisterType((*ControlEnvironmentReply)(nil), "octl.ControlEnvironmentReply")
	proto.RegisterType((*ModifyEnvironmentRequest)(nil), "octl.ModifyEnvironmentRequest")
	proto.RegisterType((*EnvironmentOperation)(nil), "octl.EnvironmentOperation")
	proto.RegisterType((*ModifyEnvironmentReply)(nil), "octl.ModifyEnvironmentReply")
	proto.RegisterType((*DestroyEnvironmentRequest)(nil), "octl.DestroyEnvironmentRequest")
	proto.RegisterType((*DestroyEnvironmentReply)(nil), "octl.DestroyEnvironmentReply")
	proto.RegisterType((*GetRolesRequest)(nil), "octl.GetRolesRequest")
	proto.RegisterType((*GetRolesReply)(nil), "octl.GetRolesReply")
	proto.RegisterType((*RoleInfo)(nil), "octl.RoleInfo")
	proto.RegisterEnum("octl.StatusUpdate_Level", StatusUpdate_Level_name, StatusUpdate_Level_value)
	proto.RegisterEnum("octl.ControlEnvironmentRequest_Optype", ControlEnvironmentRequest_Optype_name, ControlEnvironmentRequest_Optype_value)
	proto.RegisterEnum("octl.EnvironmentOperation_Optype", EnvironmentOperation_Optype_name, EnvironmentOperation_Optype_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Octl service

type OctlClient interface {
	TrackStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (Octl_TrackStatusClient, error)
	GetFrameworkInfo(ctx context.Context, in *GetFrameworkInfoRequest, opts ...grpc.CallOption) (*GetFrameworkInfoReply, error)
	Teardown(ctx context.Context, in *TeardownRequest, opts ...grpc.CallOption) (*TeardownReply, error)
	GetEnvironments(ctx context.Context, in *GetEnvironmentsRequest, opts ...grpc.CallOption) (*GetEnvironmentsReply, error)
	NewEnvironment(ctx context.Context, in *NewEnvironmentRequest, opts ...grpc.CallOption) (*NewEnvironmentReply, error)
	GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*GetEnvironmentReply, error)
	ControlEnvironment(ctx context.Context, in *ControlEnvironmentRequest, opts ...grpc.CallOption) (*ControlEnvironmentReply, error)
	ModifyEnvironment(ctx context.Context, in *ModifyEnvironmentRequest, opts ...grpc.CallOption) (*ModifyEnvironmentReply, error)
	DestroyEnvironment(ctx context.Context, in *DestroyEnvironmentRequest, opts ...grpc.CallOption) (*DestroyEnvironmentReply, error)
	GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesReply, error)
}

type octlClient struct {
	cc *grpc.ClientConn
}

func NewOctlClient(cc *grpc.ClientConn) OctlClient {
	return &octlClient{cc}
}

func (c *octlClient) TrackStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (Octl_TrackStatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Octl_serviceDesc.Streams[0], c.cc, "/octl.Octl/TrackStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &octlTrackStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Octl_TrackStatusClient interface {
	Recv() (*StatusReply, error)
	grpc.ClientStream
}

type octlTrackStatusClient struct {
	grpc.ClientStream
}

func (x *octlTrackStatusClient) Recv() (*StatusReply, error) {
	m := new(StatusReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *octlClient) GetFrameworkInfo(ctx context.Context, in *GetFrameworkInfoRequest, opts ...grpc.CallOption) (*GetFrameworkInfoReply, error) {
	out := new(GetFrameworkInfoReply)
	err := grpc.Invoke(ctx, "/octl.Octl/GetFrameworkInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *octlClient) Teardown(ctx context.Context, in *TeardownRequest, opts ...grpc.CallOption) (*TeardownReply, error) {
	out := new(TeardownReply)
	err := grpc.Invoke(ctx, "/octl.Octl/Teardown", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *octlClient) GetEnvironments(ctx context.Context, in *GetEnvironmentsRequest, opts ...grpc.CallOption) (*GetEnvironmentsReply, error) {
	out := new(GetEnvironmentsReply)
	err := grpc.Invoke(ctx, "/octl.Octl/GetEnvironments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *octlClient) NewEnvironment(ctx context.Context, in *NewEnvironmentRequest, opts ...grpc.CallOption) (*NewEnvironmentReply, error) {
	out := new(NewEnvironmentReply)
	err := grpc.Invoke(ctx, "/octl.Octl/NewEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *octlClient) GetEnvironment(ctx context.Context, in *GetEnvironmentRequest, opts ...grpc.CallOption) (*GetEnvironmentReply, error) {
	out := new(GetEnvironmentReply)
	err := grpc.Invoke(ctx, "/octl.Octl/GetEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *octlClient) ControlEnvironment(ctx context.Context, in *ControlEnvironmentRequest, opts ...grpc.CallOption) (*ControlEnvironmentReply, error) {
	out := new(ControlEnvironmentReply)
	err := grpc.Invoke(ctx, "/octl.Octl/ControlEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *octlClient) ModifyEnvironment(ctx context.Context, in *ModifyEnvironmentRequest, opts ...grpc.CallOption) (*ModifyEnvironmentReply, error) {
	out := new(ModifyEnvironmentReply)
	err := grpc.Invoke(ctx, "/octl.Octl/ModifyEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *octlClient) DestroyEnvironment(ctx context.Context, in *DestroyEnvironmentRequest, opts ...grpc.CallOption) (*DestroyEnvironmentReply, error) {
	out := new(DestroyEnvironmentReply)
	err := grpc.Invoke(ctx, "/octl.Octl/DestroyEnvironment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *octlClient) GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesReply, error) {
	out := new(GetRolesReply)
	err := grpc.Invoke(ctx, "/octl.Octl/GetRoles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Octl service

type OctlServer interface {
	TrackStatus(*StatusRequest, Octl_TrackStatusServer) error
	GetFrameworkInfo(context.Context, *GetFrameworkInfoRequest) (*GetFrameworkInfoReply, error)
	Teardown(context.Context, *TeardownRequest) (*TeardownReply, error)
	GetEnvironments(context.Context, *GetEnvironmentsRequest) (*GetEnvironmentsReply, error)
	NewEnvironment(context.Context, *NewEnvironmentRequest) (*NewEnvironmentReply, error)
	GetEnvironment(context.Context, *GetEnvironmentRequest) (*GetEnvironmentReply, error)
	ControlEnvironment(context.Context, *ControlEnvironmentRequest) (*ControlEnvironmentReply, error)
	ModifyEnvironment(context.Context, *ModifyEnvironmentRequest) (*ModifyEnvironmentReply, error)
	DestroyEnvironment(context.Context, *DestroyEnvironmentRequest) (*DestroyEnvironmentReply, error)
	GetRoles(context.Context, *GetRolesRequest) (*GetRolesReply, error)
}

func RegisterOctlServer(s *grpc.Server, srv OctlServer) {
	s.RegisterService(&_Octl_serviceDesc, srv)
}

func _Octl_TrackStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OctlServer).TrackStatus(m, &octlTrackStatusServer{stream})
}

type Octl_TrackStatusServer interface {
	Send(*StatusReply) error
	grpc.ServerStream
}

type octlTrackStatusServer struct {
	grpc.ServerStream
}

func (x *octlTrackStatusServer) Send(m *StatusReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Octl_GetFrameworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFrameworkInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OctlServer).GetFrameworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octl.Octl/GetFrameworkInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OctlServer).GetFrameworkInfo(ctx, req.(*GetFrameworkInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Octl_Teardown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeardownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OctlServer).Teardown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octl.Octl/Teardown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OctlServer).Teardown(ctx, req.(*TeardownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Octl_GetEnvironments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OctlServer).GetEnvironments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octl.Octl/GetEnvironments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OctlServer).GetEnvironments(ctx, req.(*GetEnvironmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Octl_NewEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OctlServer).NewEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octl.Octl/NewEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OctlServer).NewEnvironment(ctx, req.(*NewEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Octl_GetEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OctlServer).GetEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octl.Octl/GetEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OctlServer).GetEnvironment(ctx, req.(*GetEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Octl_ControlEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OctlServer).ControlEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octl.Octl/ControlEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OctlServer).ControlEnvironment(ctx, req.(*ControlEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Octl_ModifyEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OctlServer).ModifyEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octl.Octl/ModifyEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OctlServer).ModifyEnvironment(ctx, req.(*ModifyEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Octl_DestroyEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyEnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OctlServer).DestroyEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octl.Octl/DestroyEnvironment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OctlServer).DestroyEnvironment(ctx, req.(*DestroyEnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Octl_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OctlServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/octl.Octl/GetRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OctlServer).GetRoles(ctx, req.(*GetRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Octl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "octl.Octl",
	HandlerType: (*OctlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFrameworkInfo",
			Handler:    _Octl_GetFrameworkInfo_Handler,
		},
		{
			MethodName: "Teardown",
			Handler:    _Octl_Teardown_Handler,
		},
		{
			MethodName: "GetEnvironments",
			Handler:    _Octl_GetEnvironments_Handler,
		},
		{
			MethodName: "NewEnvironment",
			Handler:    _Octl_NewEnvironment_Handler,
		},
		{
			MethodName: "GetEnvironment",
			Handler:    _Octl_GetEnvironment_Handler,
		},
		{
			MethodName: "ControlEnvironment",
			Handler:    _Octl_ControlEnvironment_Handler,
		},
		{
			MethodName: "ModifyEnvironment",
			Handler:    _Octl_ModifyEnvironment_Handler,
		},
		{
			MethodName: "DestroyEnvironment",
			Handler:    _Octl_DestroyEnvironment_Handler,
		},
		{
			MethodName: "GetRoles",
			Handler:    _Octl_GetRoles_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TrackStatus",
			Handler:       _Octl_TrackStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/octlserver.proto",
}

func init() { proto.RegisterFile("protos/octlserver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 994 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xef, 0x6e, 0xe2, 0x46,
	0x10, 0xc7, 0xfc, 0xb9, 0x23, 0x43, 0x02, 0x66, 0x43, 0x72, 0xc4, 0x97, 0xbb, 0xd2, 0x55, 0xd5,
	0xa6, 0x6a, 0x4b, 0x5b, 0xda, 0x53, 0xef, 0xda, 0x4f, 0x49, 0x70, 0x38, 0xaa, 0xc3, 0x8e, 0x16,
	0x92, 0x93, 0x2a, 0x55, 0xa9, 0x03, 0x8b, 0x82, 0xe2, 0x78, 0xa9, 0xbd, 0x49, 0x94, 0x77, 0x69,
	0x9f, 0xa3, 0x0f, 0xd0, 0x47, 0xea, 0x0b, 0x54, 0xbb, 0x6b, 0x83, 0x31, 0xb6, 0x92, 0x6f, 0xcc,
	0xcc, 0x6f, 0xfe, 0xfd, 0x76, 0x66, 0x0c, 0xbc, 0x98, 0xfb, 0x8c, 0xb3, 0xe0, 0x5b, 0x36, 0xe6,
	0x6e, 0x40, 0xfd, 0x3b, 0xea, 0xb7, 0xa5, 0x06, 0x15, 0x85, 0x06, 0xef, 0x42, 0xc3, 0xbc, 0xa3,
	0x1e, 0xbf, 0x18, 0xd0, 0x80, 0x05, 0xef, 0xa9, 0xe3, 0xf3, 0x4b, 0xea, 0x70, 0x5c, 0x83, 0xad,
	0x21, 0x77, 0xf8, 0x6d, 0x40, 0xe8, 0x9f, 0xb7, 0x34, 0xe0, 0xf8, 0x77, 0xa8, 0x44, 0x8a, 0xb9,
	0xfb, 0x80, 0x1a, 0x50, 0x0a, 0xb8, 0xc3, 0x69, 0x53, 0x6b, 0x69, 0x07, 0x1b, 0x44, 0x09, 0xe8,
	0x2d, 0x6c, 0x05, 0x12, 0x74, 0x36, 0x9f, 0x38, 0x9c, 0x06, 0xcd, 0x7c, 0xab, 0x70, 0x50, 0xe9,
	0xa0, 0xb6, 0xc8, 0xd5, 0x1e, 0xc6, 0x4c, 0x64, 0x15, 0x88, 0xff, 0xd5, 0x60, 0x33, 0x6e, 0x47,
	0x6d, 0x28, 0xb9, 0xf4, 0x8e, 0xba, 0x32, 0x41, 0xb5, 0xd3, 0x5c, 0x0f, 0xd1, 0xfe, 0x20, 0xec,
	0x44, 0xc1, 0x50, 0x17, 0xaa, 0x37, 0x2b, 0x2d, 0x34, 0xf3, 0x2d, 0xed, 0xa0, 0xd2, 0x31, 0x94,
	0x63, 0x5a, 0x93, 0xef, 0x73, 0x24, 0xe1, 0x83, 0x7f, 0x84, 0x92, 0x8c, 0x8a, 0x36, 0xa0, 0xd4,
	0x35, 0x8f, 0xce, 0x7a, 0x7a, 0x0e, 0x95, 0xa1, 0xd8, 0xb7, 0x4e, 0x6c, 0x5d, 0x43, 0x15, 0x78,
	0xfe, 0xf1, 0x90, 0x58, 0x7d, 0xab, 0xa7, 0xe7, 0x05, 0xc2, 0x24, 0xc4, 0x26, 0x7a, 0xe1, 0xe8,
	0x39, 0x94, 0x64, 0x7c, 0xbc, 0x07, 0x2f, 0x7a, 0x94, 0x9f, 0xf8, 0xce, 0x0d, 0xbd, 0x67, 0xfe,
	0x75, 0xdf, 0x9b, 0xb2, 0x88, 0xbf, 0xbf, 0x35, 0xd8, 0x59, 0xb7, 0x09, 0x2a, 0x5b, 0x50, 0x99,
	0x2e, 0xb4, 0x93, 0x90, 0xd0, 0xb8, 0x0a, 0x7d, 0x0d, 0x75, 0xea, 0xdd, 0xcd, 0x7c, 0xe6, 0xdd,
	0x50, 0x8f, 0x07, 0xc7, 0xec, 0xd6, 0x53, 0xed, 0x95, 0xc8, 0xba, 0x01, 0xbd, 0x06, 0xf0, 0x99,
	0x4b, 0x43, 0x58, 0x41, 0xc2, 0x62, 0x9a, 0xe5, 0xd3, 0x15, 0x63, 0x4f, 0x87, 0xbf, 0x84, 0xda,
	0x88, 0x3a, 0xfe, 0x84, 0xdd, 0x7b, 0x61, 0xc9, 0x68, 0x17, 0x9e, 0xf9, 0xd4, 0x09, 0x98, 0x17,
	0xd6, 0x14, 0x4a, 0x62, 0x36, 0x96, 0xd0, 0xb9, 0xfb, 0x80, 0x9b, 0xb0, 0xdb, 0xa3, 0xdc, 0x8c,
	0x55, 0x12, 0x75, 0x1d, 0x40, 0x63, 0xcd, 0xf2, 0xb4, 0x9e, 0xdf, 0xc1, 0x66, 0xbc, 0xb5, 0x70,
	0x92, 0x76, 0xc2, 0xd7, 0x5c, 0x5a, 0x24, 0x8f, 0x2b, 0x50, 0xcc, 0xa0, 0x96, 0x00, 0xa0, 0x2a,
	0xe4, 0x67, 0x51, 0x9a, 0xfc, 0x6c, 0x22, 0xf2, 0x8f, 0x7d, 0xea, 0x70, 0x3a, 0xf9, 0x78, 0x45,
	0x3d, 0xc9, 0xe5, 0x06, 0x89, 0xab, 0x96, 0x2c, 0x15, 0xe2, 0x03, 0xde, 0x80, 0x92, 0x64, 0xb2,
	0x59, 0x6c, 0x15, 0x84, 0x56, 0x0a, 0xf8, 0x1b, 0xd8, 0xb1, 0xe8, 0x7d, 0x2c, 0x67, 0xc4, 0xe0,
	0x02, 0xae, 0xc5, 0xe1, 0xbf, 0xc0, 0x76, 0x12, 0x2e, 0x38, 0x49, 0xd6, 0xb8, 0xa8, 0x20, 0x1f,
	0x7f, 0xa7, 0x2f, 0xe4, 0x18, 0xa5, 0xe4, 0x4a, 0xb8, 0x63, 0x0b, 0xb6, 0x93, 0x40, 0x91, 0xe5,
	0x27, 0xa8, 0xc4, 0xc8, 0x92, 0xf8, 0x4c, 0x5a, 0xe3, 0x48, 0xfc, 0x8f, 0x06, 0x7b, 0xc7, 0xcc,
	0xe3, 0x3e, 0x73, 0x1f, 0xcf, 0x8e, 0x7e, 0x86, 0x22, 0x7f, 0x98, 0xab, 0xda, 0xab, 0x9d, 0xcf,
	0x55, 0xfc, 0x4c, 0xf7, 0xb6, 0x3d, 0x17, 0x68, 0x22, 0x7d, 0xb0, 0x05, 0xcf, 0x94, 0x2c, 0x56,
	0xcf, 0xb2, 0xed, 0x53, 0x3d, 0x87, 0x76, 0xa0, 0x3e, 0x1c, 0x1d, 0x92, 0xd1, 0x85, 0x69, 0x9d,
	0xf7, 0x89, 0x6d, 0x0d, 0x4c, 0x6b, 0xa4, 0x6b, 0xa8, 0x01, 0xfa, 0x70, 0x64, 0x9f, 0xae, 0x68,
	0xf3, 0x68, 0x0b, 0x36, 0x8e, 0x6d, 0xeb, 0xa4, 0xdf, 0x3b, 0x23, 0xa6, 0x5e, 0x10, 0x5b, 0x99,
	0x96, 0x59, 0x4c, 0xee, 0x14, 0x9a, 0x03, 0x36, 0x99, 0x4d, 0x1f, 0x9e, 0xd4, 0x12, 0xb0, 0x39,
	0xf5, 0x1d, 0x3e, 0x63, 0x5e, 0x34, 0x8f, 0xc6, 0x1a, 0x71, 0x76, 0x04, 0x21, 0x31, 0x34, 0xfe,
	0x4b, 0x83, 0x46, 0x1a, 0x08, 0xbd, 0x09, 0x79, 0x52, 0x57, 0xee, 0xd3, 0xec, 0x70, 0x2b, 0x14,
	0x21, 0x03, 0xca, 0x62, 0x96, 0x2c, 0xe7, 0x26, 0x1a, 0x8f, 0x85, 0x8c, 0xbf, 0x4f, 0xa1, 0xaf,
	0x06, 0x15, 0x62, 0x0e, 0xec, 0x73, 0xf3, 0x82, 0xd8, 0x1f, 0x4c, 0xbd, 0x80, 0x36, 0xa1, 0x7c,
	0xd8, 0xed, 0x2a, 0xa9, 0x88, 0xff, 0x80, 0xdd, 0x14, 0x1a, 0xc4, 0xb8, 0x9c, 0x80, 0x3e, 0x75,
	0x66, 0x2e, 0x9d, 0xd8, 0xcb, 0xd6, 0xb5, 0x47, 0x5b, 0x5f, 0xf3, 0xc1, 0x5f, 0xc1, 0x5e, 0x97,
	0x06, 0xdc, 0x67, 0x4f, 0x60, 0x5a, 0x3c, 0x58, 0x1a, 0x58, 0x3c, 0x58, 0x1d, 0x6a, 0x3d, 0xca,
	0x89, 0xd8, 0xa3, 0xe8, 0xc6, 0xbc, 0x81, 0xad, 0xa5, 0x4a, 0xd4, 0xfc, 0x59, 0x7c, 0xeb, 0x2a,
	0x9d, 0xaa, 0x2a, 0x54, 0x00, 0xe4, 0x54, 0x87, 0x5b, 0x48, 0xa0, 0x1c, 0xa9, 0x10, 0x82, 0xa2,
	0x27, 0xa8, 0x54, 0x25, 0xc8, 0xdf, 0xe2, 0xfa, 0xb9, 0x6c, 0x7c, 0x4d, 0x27, 0x92, 0xe0, 0x32,
	0x09, 0x25, 0x41, 0xfd, 0x15, 0x0b, 0xb8, 0xc4, 0xab, 0xdb, 0xb0, 0x90, 0x3b, 0xff, 0x95, 0xa0,
	0x68, 0x8f, 0xb9, 0x8b, 0xde, 0x41, 0x65, 0xe4, 0x3b, 0xe3, 0x6b, 0xf5, 0xbd, 0x42, 0xdb, 0xf1,
	0xaf, 0x57, 0x58, 0xb7, 0x51, 0x5f, 0x55, 0x8a, 0xee, 0x72, 0xdf, 0x69, 0xe8, 0x14, 0xf4, 0xe4,
	0x77, 0x02, 0xbd, 0x52, 0xd0, 0x8c, 0x6f, 0x8b, 0xf1, 0x32, 0xcb, 0x2c, 0x63, 0xa2, 0xb7, 0x50,
	0x8e, 0xee, 0x35, 0x0a, 0x37, 0x3d, 0x71, 0xea, 0x8d, 0xed, 0xa4, 0x5a, 0x79, 0x0e, 0x24, 0xdb,
	0xf1, 0xf3, 0x8d, 0xf6, 0x17, 0xb9, 0x52, 0xee, 0xbd, 0x61, 0x64, 0x58, 0x55, 0xb8, 0x5f, 0xa1,
	0xba, 0x7a, 0xf8, 0x50, 0x58, 0x79, 0xea, 0xf5, 0x34, 0xf6, 0xd2, 0x8d, 0x8b, 0x58, 0xab, 0x59,
	0xd0, 0xcb, 0xb4, 0xdc, 0x89, 0x58, 0x29, 0x17, 0x11, 0xe7, 0xd0, 0x39, 0xa0, 0xf5, 0x03, 0x81,
	0x3e, 0x79, 0xe4, 0x68, 0x19, 0xaf, 0xb2, 0x01, 0x2a, 0xee, 0x10, 0xea, 0x6b, 0x6b, 0x85, 0x5e,
	0x2b, 0xaf, 0xac, 0xb3, 0x63, 0xec, 0x67, 0xda, 0x17, 0xc5, 0xae, 0x2f, 0x47, 0x54, 0x6c, 0xe6,
	0x8e, 0x45, 0xc5, 0x66, 0xed, 0x95, 0x9c, 0x92, 0x68, 0x8d, 0xa2, 0x29, 0x49, 0x6c, 0x5a, 0x34,
	0x25, 0x2b, 0xdb, 0x86, 0x73, 0x47, 0x18, 0xf6, 0xc7, 0x57, 0xed, 0x31, 0xf5, 0xbd, 0xb6, 0xe3,
	0xce, 0xc6, 0x54, 0xa1, 0xfc, 0xf9, 0x58, 0xfd, 0xdf, 0xfc, 0x2d, 0x3f, 0xbf, 0xbc, 0x7c, 0x26,
	0xff, 0x74, 0xfe, 0xf0, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xf6, 0x02, 0x8a, 0x8f, 0x0a,
	0x00, 0x00,
}
