apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- task-manager.yaml

images:
- name: task-manager
  newName: gitlab-registry.cern.ch/aliceo2group/dockerfiles/aliecs/task-manager
  newTag: latest
