apiVersion: aliecs.alice.cern/v1alpha1
kind: Task
metadata:
  name: stfbuilder-senderoutput
  namespace: alice-tasks
spec:
  arguments:
    chans.buildertosender.0.address: ipc://@o2ipc-d7ef3du8ndmd7n8j7l30
    chans.buildertosender.0.autoBind: "0"
    chans.buildertosender.0.method: bind
    chans.buildertosender.0.rateLogging: "0"
    chans.buildertosender.0.rcvBufSize: "1000"
    chans.buildertosender.0.rcvKernelSize: "0"
    chans.buildertosender.0.sndBufSize: "4"
    chans.buildertosender.0.sndKernelSize: "0"
    chans.buildertosender.0.transport: shmem
    chans.buildertosender.0.type: push
    chans.buildertosender.numSockets: "1"
    chans.readout.0.address: ipc://@o2ipc-d7ef3du8ndmd7n8j7l2g
    chans.readout.0.method: connect
    chans.readout.0.rateLogging: "0"
    chans.readout.0.rcvBufSize: "1000"
    chans.readout.0.rcvKernelSize: "0"
    chans.readout.0.sndBufSize: "1000"
    chans.readout.0.sndKernelSize: "0"
    chans.readout.0.transport: shmem
    chans.readout.0.type: pull
    chans.readout.numSockets: "1"
    environment_id: 323ikoYJ88i
    orbit-reset-time: ""
  pod:
    hostNetwork: true
    hostIPC: true
    securityContext:
      fsGroup: 1100
      supplementalGroups: [10, 1105]
    containers:
      - name: stfbuilder-senderoutput
        image: gitlab-registry.cern.ch/aliceo2group/dockerfiles/alma9-flp-node/dd:1
        command: ["/bin/bash"]
        args:
          - "-lc"
          - "/opt/o2/bin/StfBuilder --session=default --transport=shmem --shm-segment-id=2 --shm-segment-size=33554432 --monitoring-backend='influxdb-unix:///tmp/telegraf.sock' --monitoring-process-interval='5' --discovery-partition=323ikoYJ88i --discovery-endpoint=no-op:// --detector-rdh=6 --detector-subspec=feeid --severity=info --severity-infologger=info --output-channel-name=buildertosender --shm-monitor=false --detector=TST --run-type=physics         --id 323ikp9sptz -S $CONTROL_OCCPLUGIN_ROOT/lib/ -P OCClite --color false --control-port 31001"
        securityContext:
          privileged: true
          runAsUser: 1100
          runAsGroup: 1100
          capabilities:
            add: ["IPC_LOCK"]
        env:
          - name: O2_DETECTOR
            value: "TST"
          - name: O2_PARTITION
            value: "323ikoYJ88i"
          - name: OCC_CONTROL_PORT
            value: "31001"
          - name: O2_SYSTEM
            value: "FLP"
          - name: O2_ROLE
            value: "mtichak-ost"
          - name: O2_INFOLOGGER_MODE
            value: "infoLoggerD"
          - name: DATADIST_FEE_MASK
            value: "0xffff"
          - name: CONTROL_OCCPLUGIN_ROOT
            value: "/opt/o2"
        volumeMounts:
          - name: host-shm
            mountPath: /dev/shm
          - name: group
            mountPath: /etc/group
            readOnly: true
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
          - name: tmp
            mountPath: /tmp
          - name: modules
            mountPath: /lib/modules
        imagePullPolicy: IfNotPresent
    volumes:
      - name: host-shm
        hostPath:
          path: /dev/shm
          type: Directory
      - name: group
        hostPath:
          path: /etc/group
      - name: passwd
        hostPath:
          path: /etc/passwd
      - name: tmp
        hostPath:
          path: /tmp
      - name: modules
        hostPath:
          path: /lib/modules
    imagePullSecrets:
      - name: gitlab-registry-secret
  control:
    mode: "fairmq"
    port: 31001
  bind:
    - name: readout
      type: push
      rateLogging: "0"
      addressing: ipc
      transport: shmem
      global: ""
      target: ""
  connect:
  properties:
    var1: value1
    var2: value2
  state: standby
