apiVersion: aliecs.alice.cern/v1alpha1
kind: Task
metadata:
  name: stfsender
  namespace: alice-tasks
spec:
  arguments:
    chans.buildertosender.0.address: ipc://@o2ipc-d7ef3du8ndmd7n8j7l30
    chans.buildertosender.0.method: connect
    chans.buildertosender.0.rateLogging: "0"
    chans.buildertosender.0.rcvBufSize: "1000"
    chans.buildertosender.0.rcvKernelSize: "0"
    chans.buildertosender.0.sndBufSize: "1000"
    chans.buildertosender.0.sndKernelSize: "0"
    chans.buildertosender.0.transport: shmem
    chans.buildertosender.0.type: pull
    chans.buildertosender.numSockets: "1"
    environment_id: 323ikoYJ88i
    orbit-reset-time: ""

  pod:
    hostNetwork: true
    hostIPC: true
    securityContext:
      fsGroup: 1100
      supplementalGroups: [10, 1105]
    containers:
      - name: readout
        image: gitlab-registry.cern.ch/aliceo2group/dockerfiles/alma9-flp-node/dd:1
        command: ["/bin/bash"]
        args:
          - "-c"
          # you might need to change mtichak from args to your usecase                                                                                                                                                                                                                                                                                                                                                                change this part
          - "numactl --cpunodebind=0 --preferred=0 -- /opt/o2/bin/StfSender --session=default --shm-segment-id=2 --shm-segment-size=33554432 --dd-region-size=4096 --dd-region-id=3536 --transport=shmem --input-channel-name=buildertosender --severity=info --severity-infologger=info --monitoring-backend='influxdb-unix:///tmp/telegraf.sock' --monitoring-process-interval='5' --discovery-partition=323ikoYJ88i --discovery-id=stfs-mtichak-ost-323ikoig378 --discovery-endpoint=no-op:// --discovery-net-if=ib0 --stand-alone --shm-monitor=false         --id 323ikp9tANv -S $CONTROL_OCCPLUGIN_ROOT/lib/ -P OCClite --color false --control-port 31002"
        securityContext:
          privileged: true
          runAsUser: 1100
          runAsGroup: 1100
        env:
          - name: O2_DETECTOR
            value: "TST"
          - name: O2_PARTITION
            value: "xxxxxxxx"
          - name: OCC_CONTROL_PORT
            value: "31002"
          - name: O2_SYSTEM
            value: "flp"
            # it might be necessary to change the role for your use case
          - name: O2_ROLE
            value: "mtichak"
        volumeMounts:
          - name: group
            mountPath: /etc/group
            readOnly: true
          - name: passwd
            mountPath: /etc/passwd
            readOnly: true
          - name: tmp
            mountPath: /tmp
          - name: modules
            mountPath: /lib/modules
        imagePullPolicy: IfNotPresent
    volumes:
      - name: group
        hostPath:
          path: /etc/group
      - name: passwd
        hostPath:
          path: /etc/passwd
      - name: tmp
        hostPath:
          path: /tmp
      - name: modules
        hostPath:
          path: /lib/modules
    imagePullSecrets:
      - name: gitlab-registry-secret
  control:
    mode: "fairmq"
    port: 31002
  bind:
    - name: readout
      type: push
      rateLogging: "0"
      addressing: ipc
      transport: shmem
      global: ""
      target: ""
  connect:
  properties:
    var1: value1
    var2: value2
  state: standby
