# the contents of this file are not really used, but we need an apricot instance for environment test package, which needs a non-empty file
o2:
  components:
    qc:
      TECHNICAL:
        any:
          entry: "config"
  runtime:
    aliecs:
      defaults:
        key1: value1
      vars:
        key2: value2